apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: oc-lab-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
      default: https://github.com/KevinBanegasUNITEC/ci-cd-final-project/
    - name: repo-revision
      type: string
      default: main
    - name: image-reference
      type: string
    - name: app-name
      type: string
      default: oc-lab-app

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      runAfter: ["cleanup"]
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
      workspaces:
        - name: output
          workspace: output

    - name: flake8-linting
      runAfter: ["git-clone"]
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: nose-tests
      runAfter: ["flake8-linting"]
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: buildah-task
      runAfter: ["nose-tests"]
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.image-reference)
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      runAfter: ["buildah-task"]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.image-reference) --dry-run=client -o yaml | oc apply -f -